### ISSUE TITLE
Upload 1.0.2 to Elm Package manager

### ISSUE THREAD

**Issue by cmditch** [hickscorp/elm-bigint#3]
Well, still no luck on getting the [original repo](https://github.com/gilbertkennen/bigint) to merge the PR. Any chance we can make a 1.0.2 release and just push the latest version up to elm-packages?

Thank!

**Comment by hickscorp** [comment]
@cmditch Thanks! Didn't get a notification. Can you give me a quick recap of what's happening? I thought you updated this into upstream.

**Comment by cmditch** [comment]
@hickscorp Thank you!

I think it's safe to say you are now the official maintainer of Elm's BigInt lib, as @gilbertkennen has unfortunately been quite unresponsive. See [upstream PR](https://github.com/gilbertkennen/bigint/pull/7).

I'm happy to be a co-maintainer, and give you backup if you so desire. Would hate to see it go the way of the original repo. If any features are added or optimizations made, I'd be sure to add you as a reviewer before merging any PR's.

Thanks again!

Cheers,
Coury

**Comment by hickscorp** [comment]
@cmditch Yep that sounds fair. We could load balance the tasks until more people join. I've been quite far from the Elm ecosystem for a couple of months now - focusing on backend - but I'm eager to come back to it when we kickstart our frontend :)
